### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019'

### ISSUE THREAD

**Issue by JesseWebDotCom** [pkkid/python-plexapi#240]
OS=OSX 11.0.2; Python=3.6; PlexAPI = 3.0.3

Example Code:
```python
from plexapi.server import PlexServer
baseurl = 'http://plex_server_ip:plex_server_port'
token = 'plex_server_token'
plex = PlexServer(baseurl, token)
```

Error:
```
Traceback (most recent call last):
  File "/Users/your_user_name/.homeassistant/test_plex.py", line 4, in <module>
    plex = PlexServer(baseurl, token)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/plexapi/server.py", line 103, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/plexapi/server.py", line 341, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/your_user_name/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1280, in _send_request
    self.putheader(hdr, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1212, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 5: ordinal not in range(256)
```

**Comment by Hellowlol** [comment]
Hm, im not sure we can do anything about this. (except from patching the function that fails.) What are the headers?

**Comment by JesseWebDotCom** [comment]
How do I see the headers?

**Comment by Hellowlol** [comment]
In crome open devtools (f12), click the network tab. Copy the url in the browser. Click the call in the network tab list. Click headers. Click view source, Copy the headers.

**Comment by JesseWebDotCom** [comment]
I'm not using any web browsers.  This error occurs when I call the example code above in a python script.

**Comment by Hellowlol** [comment]
Can you try from your computer and get the response headers?

http://xxx.xxxx.xxxx:32400/?X-Plex-Token=yourtoken

**Comment by JesseWebDotCom** [comment]
```
HTTP/1.1 200 OK
Content-Type: text/xml;charset=utf-8
Connection: Keep-Alive
Keep-Alive: timeout=20
X-Plex-Protocol: 1.0
Content-Encoding: gzip
X-Plex-Content-Original-Length: 2811
X-Plex-Content-Compressed-Length: 1118
Content-Length: 1118
Cache-Control: no-cache
Date: Wed, 20 Dec 2017 02:44:44 GMT
```

**Comment by JesseWebDotCom** [comment]
```
General
Request URL:http://my_ip:32400/?X-Plex-Token=my_token
Request Method:GET
Status Code:200 OK
Remote Address:my_ip:32400
Referrer Policy:no-referrer-when-downgrade

Response Headers
Cache-Control:no-cache
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:1118
Content-Type:text/xml;charset=utf-8
Date:Wed, 20 Dec 2017 02:47:31 GMT
Keep-Alive:timeout=20
X-Plex-Content-Compressed-Length:1118
X-Plex-Content-Original-Length:2811
X-Plex-Protocol:1.0

Request Headers
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.9
Cache-Control:max-age=0
Connection:keep-alive
Cookie:_ga=GA1.1.1610366511.1486822034
Host:my_ip:32400
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Query String Parameters
X-Plex-Token:my_token
```

**Comment by pkkid** [comment]
Do you happen to use any special characters in your Plex Server name or any of the Library names?

**Comment by pkkid** [comment]
..or perhaps your username even?

**Comment by JesseWebDotCom** [comment]
No.  All characters are letters or spaces (ex. MYFLIX, Adult Movies, JESSEWEBDOTCOM)

**Comment by pkkid** [comment]
What about the right quote mark anywhere?
\u2019 = http://www.fileformat.info/info/unicode/char/2019/index.htm

**Comment by JesseWebDotCom** [comment]
Not in the Username, server name, or Library Names.  However and if it matters, "Bob's Burgers" is in my On Deck

**Comment by JesseWebDotCom** [comment]
Got any code for me to modify/run that could pinpoint the offender?

**Comment by pkkid** [comment]
Let me try adding that show to my setup and get back. I can't do it tonight tho.

**Comment by JesseWebDotCom** [comment]
My laptop (where I'm running the script from - this is NOT my plex server) also has a single quote in its name (ex. Jesse's MacBook Pro).  That's probably the problem.

**Comment by JesseWebDotCom** [comment]
That is definitely it - as seen when debugging in pycharm:
```
<class 'tuple'>: (<class 'UnicodeEncodeError'>, UnicodeEncodeError('latin-1', 'Jesse’s MacBook Pro', 5, 6, 'ordinal not in range(256)'), None)
```

**Comment by pkkid** [comment]
Awesome, good find.

**Comment by JesseWebDotCom** [comment]
Thanks for your help and quick responses.  While ideally the code would be able to handle these types of characters, I fixed the problem on my end by changing my hostname:
```
sudo scutil --set HostName "Jesses Macbook Pro"
```

**Comment by pkkid** [comment]
Yea, we should be able to handle it. I'm wondering if this is a plexapi issue or a python requests issue. We don't really call out needing to use (or care about) the hostname anywhere in that code path.

**Comment by Hellowlol** [comment]
I still dont understand why you got the original traceback. Was the host name included in the headers?
